#!/bin/bash
# --- Configuration ---
PLUGIN_NAME="logsviewer"
AUTHOR="Lazaros Chalkidis"
GITHUB_USER="Lazaros-Chalkidis"
GIT_URL="https://github.com/Lazaros-Chalkidis/unraid-logsviewer"
PACKAGE_DIR_FINAL="packages"
PACKAGE_DIR_TEMP="package-temp"

# --- Versioning ---
BASE_VERSION=$(date +'%Y.%m.%d')
LETTER_SUFFIX="$1"
STAGE_INPUT="$2"
STAGE_SUFFIX=""

if [[ -n "$STAGE_INPUT" && "$STAGE_INPUT" != "release" ]]; then
    STAGE_SUFFIX="-${STAGE_INPUT}"
fi

VERSION="${BASE_VERSION}${LETTER_SUFFIX}${STAGE_SUFFIX}"

# --- Branch & URL Logic based on 'dev' flag ---
LOCAL_INSTALL="${3:-}"

if [[ "$LOCAL_INSTALL" == "local" ]]; then
  # Settings for a 'local' build (no URL download - embed package in PLG)
  BRANCH="local"
  PLUGIN_URL_STRUCTURE=""
  CHANGES_TEXT="- Local build (embedded package inside PLG; no URL download)."
elif [[ "$STAGE_INPUT" == "dev" ]]; then
  # Settings for a 'dev' build
  BRANCH="dev"
  PLUGIN_URL_STRUCTURE="&gitURL;/raw/&branch;/packages/&name;-&version;.txz"
  CHANGES_TEXT="- Development build from the 'dev' branch. For testing purposes only."
else
  # Settings for a 'release' build
  BRANCH="main"
  PLUGIN_URL_STRUCTURE="&gitURL;/releases/download/&version;/&name;-&version;.txz"
  CHANGES_TEXT="- Automated main build release."
fi


# --- Changelog from CHANGELOG.md (optional) ---
CHANGELOG_MD_FILE="CHANGELOG.md"
if [[ -f "${CHANGELOG_MD_FILE}" ]]; then
  # Use the full markdown contents as the changelog shown in Unraid (the "!" icon).
  CHANGES_BLOCK="$(cat "${CHANGELOG_MD_FILE}")"
else
  # Fallback to a minimal autogenerated changelog.
  CHANGES_BLOCK=$'### ${VERSION}\n${CHANGES_TEXT}'
fi

# --- Build Process ---
echo "Starting build for version ${VERSION} on branch ${BRANCH}..."

# Clean up
rm -rf ${PACKAGE_DIR_TEMP}
rm -rf ${PACKAGE_DIR_FINAL}
mkdir -p ${PACKAGE_DIR_TEMP}
mkdir -p ${PACKAGE_DIR_FINAL}

# Create target structure and copy files
PLUGIN_DEST_PATH="${PACKAGE_DIR_TEMP}/usr/local/emhttp/plugins/${PLUGIN_NAME}"
mkdir -p "${PLUGIN_DEST_PATH}"
cp -R source/* "${PLUGIN_DEST_PATH}/"

# Create branch metadata file
cat > "${PLUGIN_DEST_PATH}/branch.meta" << METAEOF
BRANCH="${BRANCH}"
IS_MAIN_BRANCH=$([[ "$BRANCH" == "main" ]] && echo "1" || echo "0")
METAEOF

# Set correct permissions before packaging
find "${PLUGIN_DEST_PATH}" -type d -exec chmod 755 {} \;
find "${PLUGIN_DEST_PATH}" -type f -exec chmod 644 {} \;


# Create .txz archive
FILENAME="${PLUGIN_NAME}-${VERSION}"
PACKAGE_PATH="${PACKAGE_DIR_FINAL}/${FILENAME}.txz"

echo "Creating package: ${FILENAME}.txz"
tar -C ${PACKAGE_DIR_TEMP} -cJf "${PACKAGE_PATH}" usr

if [ ! -f "${PACKAGE_PATH}" ]; then
    echo "❌ Error: Package creation failed!"
    exit 1
fi

echo "✅ Package created: $(du -h ${PACKAGE_PATH} | cut -f1)"

# Compute MD5 for PLG integrity check
PACKAGE_MD5=$(md5sum "${PACKAGE_PATH}" | cut -d' ' -f1)
echo "🔐 MD5: ${PACKAGE_MD5}"

# --- Helper: base64 without line breaks (portable-ish) ---
b64_nolf() {
  if base64 --help 2>/dev/null | grep -q -- "-w"; then
    base64 -w 0 "$1"
  else
    base64 "$1" | tr -d '\n'
  fi
}

# --- Create .PLG file ---
echo "Generating ${PLUGIN_NAME}.plg for '${BRANCH}' target..."

if [[ "$LOCAL_INSTALL" == "local" ]]; then
  PACKAGE_B64="$(b64_nolf "${PACKAGE_PATH}")"

  cat > "${PLUGIN_NAME}.plg" << EOF
<?xml version='1.0' standalone='yes'?>
<!DOCTYPE PLUGIN [
 <!ENTITY name "${PLUGIN_NAME}">
 <!ENTITY author "${AUTHOR}">
 <!ENTITY version "${VERSION}">
 <!ENTITY branch "${BRANCH}">
 <!ENTITY gitURL "${GIT_URL}">
 <!ENTITY selfURL "&gitURL;/raw/&branch;/&name;.plg">
 <!ENTITY launch "Settings/LogsviewerSettings">
]>

<PLUGIN name="&name;" Title="Logs Viewer" author="&author;" version="&version;" pluginURL="&selfURL;" launch="&launch;" icon="logsviewerplugin.png" min="6.9.0" support="&gitURL;/issues">

<DESCRIPTION>
Logs Viewer is a modern and fast log viewer, featuring a Dashboard widget and a Tools page.
View System, Docker, and VM logs in one place with search, filtering, optional syntax highlighting (two modes), autoscroll, export, and helpful status counters.
Fully configurable, lightweight, and safe for large logs, with sensible defaults and performance - friendly limits.
</DESCRIPTION>

<CHANGES>
${CHANGES_BLOCK}
</CHANGES>

<!-- Local install: embed package as base64, decode on the Unraid flash, then install -->
<FILE Name="/boot/config/plugins/&name;/&name;-&version;.txz.b64">
  <INLINE>${PACKAGE_B64}</INLINE>
</FILE>

<FILE Run="/bin/bash">
<INLINE>
# Decode embedded txz
mkdir -p /boot/config/plugins/&name;
base64 -d /boot/config/plugins/&name;/&name;-&version;.txz.b64 > /boot/config/plugins/&name;/&name;-&version;.txz 2>/dev/null || \
  base64 -D /boot/config/plugins/&name;/&name;-&version;.txz.b64 > /boot/config/plugins/&name;/&name;-&version;.txz
rm -f /boot/config/plugins/&name;/&name;-&version;.txz.b64

# Install package
upgradepkg --install-new /boot/config/plugins/&name;/&name;-&version;.txz
</INLINE>
</FILE>

<FILE Name="/boot/config/plugins/&name;/&name;.cfg">
  <INLINE>
    REFRESH_ENABLED="1"
    REFRESH_INTERVAL="10"
    ENABLED_SCRIPTS=""
    SHOW_IDLE_LOGS="0"
    VERSION_OVERRIDE="auto"
  </INLINE>
</FILE>

<FILE Run="/bin/bash">
<INLINE>
# Fix ownership and permissions after unpacking on the Unraid server
chown -R root:root /usr/local/emhttp/plugins/&name;
chmod -R 755 /usr/local/emhttp/plugins/&name;
find /usr/local/emhttp/plugins/&name; -type f -exec chmod 644 {} \;

echo ""
echo "----------------------------------------------------"
echo " &name; (&branch; build) has been installed."
echo " Version: &version;"
echo "----------------------------------------------------"
echo ""
</INLINE>
</FILE>

<FILE Run="/bin/bash" Method="remove">
<INLINE>
removepkg &name;-&version;
rm -rf /usr/local/emhttp/plugins/&name;
rm -rf /boot/config/plugins/&name;

echo ""
echo "----------------------------------------------------"
echo " &name; has been removed."
echo "----------------------------------------------------"
echo ""
</INLINE>
</FILE>

</PLUGIN>
EOF

else

  cat > "${PLUGIN_NAME}.plg" << EOF
<?xml version='1.0' standalone='yes'?>
<!DOCTYPE PLUGIN [
 <!ENTITY name "${PLUGIN_NAME}">
 <!ENTITY author "${AUTHOR}">
 <!ENTITY version "${VERSION}">
 <!ENTITY branch "${BRANCH}">
 <!ENTITY gitURL "${GIT_URL}">
 <!ENTITY pluginURL "${PLUGIN_URL_STRUCTURE}">
 <!ENTITY selfURL "&gitURL;/raw/&branch;/&name;.plg">
 <!ENTITY md5 "${PACKAGE_MD5}">
 <!ENTITY launch "Settings/LogsviewerSettings">
]>

<PLUGIN name="&name;" Title="Logs Viewer" author="&author;" version="&version;" pluginURL="&selfURL;" launch="&launch;" icon="logsviewerplugin.png" min="6.9.0" support="&gitURL;/issues">

<DESCRIPTION>
Logs Viewer is a modern and fast log viewer, featuring a Dashboard widget and a Tools page.
View System, Docker, and VM logs in one place with search, filtering, optional syntax highlighting (two modes), autoscroll, export, and helpful status counters.
Fully configurable, lightweight, and safe for large logs, with sensible defaults and performance-friendly limits.
</DESCRIPTION>

<CHANGES>
${CHANGES_BLOCK}
</CHANGES>

<FILE Name="/boot/config/plugins/&name;/&name;-&version;.txz" Run="upgradepkg --install-new">
<URL>&pluginURL;</URL>
<MD5>&md5;</MD5>
</FILE>

<FILE Name="/boot/config/plugins/&name;/&name;.cfg">
  <INLINE>
    REFRESH_ENABLED="1"
    REFRESH_INTERVAL="10"
    ENABLED_SCRIPTS=""
    SHOW_IDLE_LOGS="0"
    VERSION_OVERRIDE="auto"
  </INLINE>
</FILE>

<FILE Run="/bin/bash">
<INLINE>
# Fix ownership and permissions after unpacking on the Unraid server
chown -R root:root /usr/local/emhttp/plugins/&name;
chmod -R 755 /usr/local/emhttp/plugins/&name;
find /usr/local/emhttp/plugins/&name; -type f -exec chmod 644 {} \;

echo ""
echo "----------------------------------------------------"
echo " &name; (&branch; build) has been installed."
echo " Version: &version;"
echo "----------------------------------------------------"
echo ""
</INLINE>
</FILE>

<FILE Run="/bin/bash" Method="remove">
<INLINE>
removepkg &name;-&version;
rm -rf /usr/local/emhttp/plugins/&name;
rm -rf /boot/config/plugins/&name;

echo ""
echo "----------------------------------------------------"
echo " &name; has been removed."
echo "----------------------------------------------------"
echo ""
</INLINE>
</FILE>

</PLUGIN>
EOF

fi

# Clean up temp directory
rm -rf ${PACKAGE_DIR_TEMP}

echo ""
echo "🎉 Build completed successfully!"
echo "📦 Version: ${VERSION}"
echo "📁 Package: ${PACKAGE_PATH}"
echo "📄 PLG file: ${PLUGIN_NAME}.plg"